### ISSUE TITLE
Support for additional cleaning modes

### ISSUE THREAD

**Issue by nchieffo** [edenhaus/ha-prosenic#3] opened 2020-05-27 16:29 UTC
Hello, I have cocosmart 800T which I think is similar to the 820T
My robot has additional cleaning modes other than the ones exposed in your integration: 
- Single room cleaning
- Edge clean
- Automatically mop

Is it possible to support them?
Thanks

**Comment by edenhaus** [comment] 2020-05-27 20:15
Hi,

what you mean by automatically mop? On the 820 you have to replace the dust container with the water tank. When you replace it, the vacuum automatically switches to the mopping mode.

The other two are partly already implemented. Home Assistant has no built in funtion to set the mode, so I will create a custom service. The problem is only, that due the coronavirus I can‘t travel to Vienna and therefore not test the code. Hopefully in two week I can go there.

**Comment by nc4891** [comment] 2020-05-27 20:47
I don't know what this "automatically mop" does, but I have it in my proscenic home app.
I don't use mop so I really don't know.

Anyway I think it would be useful to have "preferred mode" option (maybe in yaml configuration) to use the "single room cleaning mode" instead of the "auto cleaning mode".
I really dislike the auto cleaning mode because when the robot thinks the room is clean, instead of just stopping it starts to look for its charging base (which often is not the room, so most of the times it wastes battery going around)

Thanks for your work

**Comment by edenhaus** [comment] 2020-05-27 21:08
I have seen the button in the app and he starts the auto cleaning mode. So it‘s already supported.

I think instead of the preferred mode, I would say we start normally the last selected mode. So it‘s easier to change and no restart is required.

At the moment I have no time, would you like to give it a try? It should not be hard to implement it.

**Comment by nc4891** [comment] 2020-05-27 21:21
That's a good idea! But how to change the preferred mode?
Sorry I'm not python expert

**Comment by edenhaus** [comment] 2021-02-08 22:30
Closing as I archive this repository.

**Closed as completed by edenhaus** 2021-02-08 22:30 UTC
Labels: enhancement
